<div id="gird">
    <div class="inner">
        <div class="book-title"><h1>第二章 配置</h1></div>
        <hr>
        <div class="book-content">
            <div>
                本框架全局配置在Common/Config下的config.php中,events.php为事务管理器配置,filetype.php为文件后缀和content-type的对应数据,
                可用于上传文件时判断伪后缀文件,request.php是处理request数据的配置,zh_CN是验证类的中文语言数据(用到验证类才有用),每个
                模块还可以有自己单独的事务管理器配置,存放在模块根目录下,命名为events.php
                <br>
                Common下的function.php为公共函数
            </div>
        </div>
    </div>
</div>
