<div id="gird">
    <div class="inner">
        <div class="book-title"><h1>2.4 其他配置</h1></div>
        <hr>
        <div class="book-content">
            <h2>Config/zh_CN.php</h2>
            <div>
                这个就是中午的语言包,验证类用的,不详细讲了.
            </div>
            <h2>Config/filetype.php</h2>
            <div>
                这个是文件后缀和contentType的对应,可能没收集全.
            </div>
            <h2>Config/request.php</h2>
            <div>
                这个是request数据处理的配置,可以对$_GET和$_POST等数据做处理.可用于过滤等
                <h3>示例如下</h3>
                <div class="code">
                    'server' => function ($data) {
                    <div class="in_array">
                        unset($data['REQUEST_TIME']);<span class="note">//过滤$_SERVER['REQUEST_TIME']</span><br>
                        return $data;
                    </div>
                    },<br>
                    'get' => function ($data) {
                    <div class="in_array">
                        return $data;
                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
