<div id="gird">
	<div class="inner">
		<div class="book-title" menu="1"><h1>序言</h1></div>
		<div id="987" class="book-content">
			<a href="http://t.qq.com/topthink" target="_blank"><img src="http://v.t.qq.com/cgi-bin/signature?name=topthink&sign=2fec1e2da01d2d5fe4d5b549ef6d3829349e16d2&type=1" /></a> <br />
<br /><h3><font color="red">本手册仅针对3.1版本，3.2在线手册 <a href="http://document.thinkphp.cn/manual_3_2.html" target="_blank">请看这里</a>！</font></h3><br /><h3>版权申明</h3>发布本资料须遵守开放出版许可协议 1.0 或者更新版本。<br />
未经版权所有者明确授权，禁止发行本文档及其被实质上修改的版本。 <br />
未经版权所有者事先授权，禁止将此作品及其衍生作品以标准（纸质）书籍形式发行。 <br />
如果有兴趣再发行或再版本手册的全部或部分内容，不论修改过与否，或者有任何问题，请联系版权所有者 liu21st@gmail.com。<br />
对ThinkPHP有任何疑问或者建议，请进入官方讨论区 [ <a href="http://www.thinkphp.cn/topic" target="_blank">http://www.thinkphp.cn/topic</a> ] 发布相关讨论。并在此感谢ThinkPHP团队的所有成员和所有关注和支持ThinkPHP的朋友。 <br />
有关ThinkPHP项目及本文档的最新资料，请及时访问ThinkPHP项目主站 <a href="http://thinkphp.cn" target="_blank">http://thinkphp.cn</a>。<br />
本文档的版权归ThinkPHP文档小组所有，本文档及其描述的内容受有关法律的版权保护，对本文档内容的任何形式的非法复制，泄露或散布，将导致相应的法律责任。		</div><div id="548" class="book-content">
			<h3>作者和贡献者</h3>本手册内容由ThinkPHP创始人刘晨（流年）撰写，以及文档小组的成员参与贡献。<br />
他们是Misn、<a href="http://www.zjzit.cn/" target="_blank">麦当苗儿</a>、luofei、<a href="http://www.hdj.me/" target="_blank">deeka</a>、<a href="http://code-tech.diandian.com" target="_blank">yangweijie</a>、<a href="http://www.4wei.cn/" target="_blank">vus520</a>。<br />
并在此对所有参与手册纠错和建议的朋友表示感谢！		</div><div id="549" class="book-content">
			<h3>捐赠我们</h3><b><font color="red">ThinkPHP一直在致力于简化企业和个人的WEB应用开发，您的帮助是对我们最大的支持和动力！<br />
我们的团队七年来一直在坚持不懈地努力，并坚持开源和免费提供使用，帮助开发人员更加方便的进行WEB应用的快速开发，如果您对我们的成果表示认同并且觉得对你有所帮助我们愿意接受来自各方面的捐赠^_^。</font></b><br />
<a href="http://me.alipay.com/thinkphp" target="_blank"><img src="http://thinkphp.cn/Public/Images/btn-index.png" /></a>		</div>
		
		<div style="width: 970px; height: 90px; margin: 10px auto;">
			<script async src="http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<ins class="adsbygoogle"
			     style="display:inline-block;width:970px;height:90px"
			     data-ad-client="ca-pub-2076739524120221"
			     data-ad-slot="1810691041"></ins>
			<script>
				(adsbygoogle = window.adsbygoogle || []).push({});
			</script>
		</div>
		<div id="comment" class="comment" data-url="{:U('Comment/getList')}">
	<div class="title t_loading">评论加载中...</div>
	<!-- 评论 -->
	<div id="template" class="box hide">
		<div class="userheader"><img></div>
		<div class="content">
			<div><span class="username"></span> · <span class="datetime"></span></div>
			<div class="comment-content">
				<a class="add-reply" href="javascript:;">回复</a>
			</div>
		</div>
	</div>
	<!-- /评论 -->

	<!-- <span class="at">@麦当苗儿 </span> -->

	<div id="comment-area" class="comment-area">
		<!-- 有评论前 -->
		<div id="comment-info" class="cmt-login hide">
			您需要登录后才可以评论 <a href="http://www.thinkphp.cn/member/login.html">登录</a>
		</div>
		<!-- /有评论前 -->

		<!-- 有评论后 -->
		<form id="comment-update" class="cmt-form hide" action="/Comment/update.html" method="post">
			<!-- 评论头像 -->
			<div class="cmt-top">
				<img class="user-img">
				<!-- <span class="nick"></span> -->
			</div>
			<!-- /评论头像 -->
			<div class="cmt-content"><textarea placeholder="在这里输入评论内容..." name="content"></textarea></div>
			<div class="cf">
				<div class="fr">
					<input type="hidden" name="book_id" value="1">
					<input type="hidden" name="record_id" value="1">
					<input type="submit" value="评论[Ctrl+Enter]" class="btn">
				</div>
				<div class="tips">评论支持使用[code][/code]标签添加代码</div>
			</div>
		</form>
		<!-- /有评论后 -->
	</div><!-- end .comment-area -->
</div>
<script type="text/javascript">
(function($){
	var self   = $("#comment");
	var url    = self.data("url"), title = self.find(".title"), num;
	var reply  = $('<input type="hidden" name="reply" value="0">');
	var update = $("#comment-update")
					 .bind("success", function(e, data){
					 	this.reset();
					 	self.trigger("insertreview", data);
					 	data.reply == 0 && num.text(parseInt(num.text()) + 1);
					 	prettyPrint();
					 });
	var data   = update.find("input[type=hidden]").serialize();
	var success = function(list){
		var list = list.data, data;
		update.find(":submit").before(reply);
		if(list.count != undefined)
			num = title.removeClass("t_loading")
					   .html("共<span>" + list.count + "</span>条评论").find("span");
		if($.isArray(list.comment)){
			for(i in list.comment){
				data = list.comment[i];
				data.list = 1;
				self.trigger("insertreview", data);
			}
		}
		if($.isArray(list.reply)){
			for(i in list.reply){
				data = list.reply[i];
				data.list = 1;
				self.trigger("insertreview", data);
			}
		}
		prettyPrint();
	}

	update.find("textarea").on("keydown", function(e){
		e.stopPropagation();
		if(e.ctrlKey && e.which ==13){
			update.submit();
		}
	});

	//绑定评论事件
	self.bind("get", function(){ $.get(url, data, success, "json") }).trigger("get");
	self.click(function(e){e.stopPropagation()});

	var template = $("#template"), commentArea = $("#comment-area");
	template.find(".add-reply").click(function(){
		var content = $(this).parent().parent(),
			name    = $(this).parent().prev().find("a").text(),
			attxt   = "";
		commentArea.css("opacity", 0);
		if(content.parent().is(".reply")){
			content = content.parent().siblings(".content");
		}
		commentArea.find("textarea").val(attxt);
		reply.val(content.after(commentArea).parent().attr("id").replace("comment-", ""));
		commentArea.animate({"opacity" : 1});
		$(document).one("click", function(){
			commentArea.animate({"opacity" : 1});
			template.after(commentArea);
			reply.val(0);
			commentArea.fadeIn();
		});
	});

	self.bind("insertreview", function(e, data){
		var tpl = template.clone(true, true).attr("id", "comment-" + data.id); 
		tpl.find("img").attr("src", avatar(data.uid)).error(function(e){this.src = avatar(0)});
		tpl.find(".content .username").text(data.username);
		tpl.find(".content .datetime").text(format(data.create_time));
		tpl.find(".comment-content").prepend(parse_content(data.content));
		if(data.reply == 0){
			data.list ? tpl.insertBefore(template) : tpl.insertAfter(title);
			tpl.fadeIn();
		} else {
			tpl.addClass("reply").appendTo($("#comment-" + data.reply)).fadeIn();
		}
	});

	//评论框自动高度
	update.find("textarea").on("keyup keydown", function(){
	 	$(this).height(this.scrollHeight);
	})

	//发布评论
	$("#comment-update")
		.bind("loading", function(e, msg){
			$(this).find("input,textarea").attr("disabled", true).end()
				   .find(".tips").addClass("loading").text(msg || "正在提交，请稍后...");
		})
		.bind("removeloading", function(){
			$(this).find("input,textarea").attr("disabled", false).end()
				   .find(".tips").removeClass("loading").text("");
		})
		.bind("error", function(e, msg){
			$(this).find(".tips").addClass("error").text(msg || "服务器返回数据错误");
		})
		.bind("removeerror", function(){
			$(this).find(".tips").removeClass("error").text("");
		})
		.submit(function(){
			var _self = $(this).trigger("removeerror"); 
			$.post(
				_self.attr("action"),
				_self.serialize(),
				function(data){
					_self.trigger("removeloading");
					data.status ? _self.trigger("success", data.data) 
								: _self.trigger("error", data.info);
				},
				"json"
			);
			_self.trigger("loading");
			return false;
		});

})(jQuery);

function format(timestamp){
	var nowTime = parseInt((new Date())/1000);
	var time    = nowTime - timestamp;

	if(time < 5){
		return "刚刚";
	} else if(time < 60){
		return time + "秒前";
	} else if(time < 3600){
		return parseInt(time/60) + "分钟前";
	} else if(time < 3600 * 24){
		return parseInt(time/3600) + "小时前";
	} else if(date("Y") == date("Y", timestamp)){
		return date("m-d H:i", timestamp);
	} else {
		return date("Y-m-d", timestamp);
	}
}

/**
 * 和PHP一样的时间戳格式化函数
 * @param  {string} format    格式
 * @param  {int}    timestamp 要格式化的时间 默认为当前时间
 * @return {string}           格式化的时间字符串
 */
function date(format, timestamp){ 
    var a, jsdate=((timestamp) ? new Date(timestamp*1000) : new Date());
    var pad = function(n, c){
        if((n = n + "").length < c){
            return new Array(++c - n.length).join("0") + n;
        } else {
            return n;
        }
    };
    var f = {
        // Day  Y-m-d H:i:s
        d: function(){return pad(f.j(), 2)},
        j: function(){return jsdate.getDate()},

        // Month
        m: function(){return pad(f.n(), 2)},
        n: function(){return jsdate.getMonth() + 1},

        Y: function(){return jsdate.getFullYear()},

        // Time
        H: function(){return pad(jsdate.getHours(), 2)},
        i: function(){return pad(jsdate.getMinutes(), 2)},
        s: function(){return pad(jsdate.getSeconds(), 2)}

    };

    return format.replace(/[\\]?([a-zA-Z])/g, function(t, s){
        if( t!=s ){
            // escaped
            ret = s;
        } else if( f[s] ){
            // a date function exists
            ret = f[s]();
        } else{
            // nothing special
            ret = s;
        }
        return ret;
    });
}

function avatar(uid){
	var avatar = [];
	if(uid && $.isNumeric(uid)){
		if((uid = uid + "").length < 10){
	        uid = new Array(11 - uid.length).join("0") + uid;
	    }

	   	avatar[0] = uid.substr(0,3);
	   	avatar[1] = uid.substr(3,3);
	   	avatar[2] = uid.substr(6,2);
	   	avatar[3] = uid.substr(8,2);
	   	
	   	avatar = "avatar/" + avatar.join('/') + "/original_44_44.gif";
	} else {
		avatar = 'avatar/44_44.png';
	}

	return 'http://www.thinkphp.cn/' + avatar;
}
</script>
	</div>
</div>
