<div id="gird">
    <div class="inner">
        <div class="book-title"><h1>简介</h1></div>
        <hr>
        <div class="book-content">
            <h2>特别的框架</h2>
            <h3>mvc-l/mvc</h3>
            <div>
                &nbsp;&nbsp;&nbsp;&nbsp;现今主流框架基本都是分成model, view, controller三层,在开发中,一般需要从数据库中获取
                到数据,然后经过一番逻辑处理之后再抛给视图层,可能因为每个人习惯不同,或者是每个人个性不同,有的人喜欢把这么一番逻
                辑处理放在controller层,有的人喜欢放在model层,其实在没有规范的情况下,放在哪个层都是允许的,或许我们在阅读项目时
                或者做单元测试的时候会很纠结.因为每个人的习惯不同,导致我们要阅读项目逻辑时会很麻烦.这便是重点.<br>
                &nbsp;&nbsp;&nbsp;&nbsp;框架中特别加入logic层,可用于专门处理逻辑,这里要特别鸣谢我曾经的导师(迪哥),这个想法是
                当时我们搭建当时的项目框架时他想出来的,这个框架中我沿用了当时的这个想法,但在我的框架中,logic层不是必须的,毕竟还
                是会有人用习惯了mvc模式,不愿意加多个locig层,也有一些项目确实没有逻辑处理,例如新闻网站等等等等...
            </div>
            <h3>事务管理器</h3>
            <div>
                &nbsp;&nbsp;&nbsp;&nbsp;因为之前用过zf2,觉得事务管理器这东西实在太猛了,
            </div>
        </div>
    </div>
</div>
