<div id="selector">
    <div class="inner">
        <div class="book-menu">
            <div class="list">
                <ul>
                    <li class="child">
                        <a class="title <?php if ($this->controller === 'index') echo 'selected'; ?>" href="/manual/index.html" title="首页">首页</a>
                    </li>
                    <li class=" child">
                        <a class="title <?php if ($this->controller === 'start') echo 'selected'; ?>" href="/manual/start.html" title="入门">第1章&nbsp;入门</a>
                    </li>	
                    <li class="<?php if ($this->controller === 'config') echo 'show'; ?> child">
                        <a class="title <?php if ($this->action === 'config-index') echo 'selected'; ?>" href="/manual/config.html" title="入门">第2章&nbsp;配置</a>
                        <ul>
                            <li>
                                <a class="title <?php if ($this->action === 'config-global') echo 'selected'; ?>" href="/manual/config-global.html">2.1&nbsp;全局配置</a>
                            </li>
                            <li>
                                <a class="title <?php if ($this->action === 'config-events') echo 'selected'; ?>" href="/manual/config-events.html">2.2&nbsp;事务配置</a>
                            </li>
                            <li>
                                <a class="title <?php if ($this->action === 'config-module') echo 'selected'; ?>" href="/manual/config-module.html">2.3&nbsp;模块配置</a>
                            </li>
                            <li>
                                <a class="title <?php if ($this->action === 'config-others') echo 'selected'; ?>" href="/manual/config-others.html">2.4&nbsp;其他配置</a>
                            </li>
                        </ul>					
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>