<div id="selector">
    <div class="inner">
        <div class="book-menu">
            <div class="list">
                <?php isset($this->action) || $this->action = 'index' ?>
                <ul>
                    <li class="child">
                        <a class="title <?php if ($this->controller === 'index') echo 'selected'; ?>" href="/manual/index.html" title="首页">首页</a>
                    </li>
                    <li class=" child">
                        <a class="title <?php if ($this->controller === 'start') echo 'selected'; ?>" href="/manual/start.html" title="入门">第1章&nbsp;入门</a>
                    </li>	
                    <li class="<?php if ($this->controller === 'config') echo 'show'; ?> child">
                        <a class="title <?php if ($this->action === 'config-index') echo 'selected'; ?>" href="/manual/config.html" title="配置">第2章&nbsp;配置</a>
                        <ul>
                            <li>
                                <a class="title <?php if ($this->action === 'config-global') echo 'selected'; ?>" href="/manual/config-global.html">2.1&nbsp;全局配置</a>
                            </li>
                            <li>
                                <a class="title <?php if ($this->action === 'config-events') echo 'selected'; ?>" href="/manual/config-events.html">2.2&nbsp;事务配置</a>
                            </li>
                            <li>
                                <a class="title <?php if ($this->action === 'config-module') echo 'selected'; ?>" href="/manual/config-module.html">2.3&nbsp;模块配置</a>
                            </li>
                            <li>
                                <a class="title <?php if ($this->action === 'config-others') echo 'selected'; ?>" href="/manual/config-others.html">2.4&nbsp;其他配置</a>
                            </li>
                        </ul>					
                    </li>
                    <li class="<?php if ($this->controller === 'system') echo 'show'; ?> child">
                        <a class="title <?php if ($this->action === 'system-index') echo 'selected'; ?>" href="/manual/system.html" title="系统核心">第3章&nbsp;系统核心</a>
                        <ul>
                            <li>
                                <a class="title <?php if ($this->action === 'system-router') echo 'selected'; ?>" href="/manual/system-router.html">3.1&nbsp;路由</a>
                            </li>
                            <li>
                                <a class="title <?php if ($this->action === 'system-event') echo 'selected'; ?>" href="/manual/system-event.html">3.2&nbsp;事务管理器</a>
                            </li>
                            <li>
                                <a class="title <?php if ($this->action === 'system-controller') echo 'selected'; ?>" href="/manual/system-controller.html">3.3&nbsp;控制器</a>
                            </li>
                            <li>
                                <a class="title <?php if ($this->action === 'system-logic') echo 'selected'; ?>" href="/manual/system-logic.html">3.4&nbsp;逻辑层</a>
                            </li>
                            <li>
                                <a class="title <?php if ($this->action === 'system-model') echo 'selected'; ?>" href="/manual/system-model.html">3.5&nbsp;模型层</a>
                            </li>
                            <li>
                                <a class="title <?php if ($this->action === 'system-view') echo 'selected'; ?>" href="/manual/system-view.html">3.6&nbsp;视图层</a>
                            </li>
                        </ul>					
                    </li>
                    <li class="<?php if ($this->controller === 'library') echo 'show'; ?> child">
                        <a class="title <?php if ($this->action === 'library-index') echo 'selected'; ?>" href="/manual/library.html" title="类库">第4章&nbsp;类库和函数</a>
                        <ul>
                            <li>
                                <a class="title <?php if ($this->action === 'library-db') echo 'selected'; ?>" href="/manual/library-db.html">4.1&nbsp;db类</a>
                            </li>
                        </ul>					
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>