<div id="gird">
    <div class="inner">
        <div class="book-title"><h1>第一章 入门</h1></div>
        <hr>
        <div class="book-content">
            <h2>环境要求</h2>
            因为本框架运用了命名空间,匿名函数等5.3以上特性,所以只支持php5.3以上版本,可运行于包括Apache、IIS和nginx在内的多种WEB服务器和模式,
            目前仅支持Mysql数据库链接(个人能力有限,其他数据库支持后期开发,敬请期待)
            <h2>获取框架</h2>
            <a href="https://github.com/gpYang/ygp">框架下载地址</a>
            下载解压即可用
            <h2>目录结构</h2>
            <table border="0" cellspacing="1" cellpadding="0">
                <tbody>
                    <tr class="add"><th>目录/文件</th><th>说明</th></tr>
                    <tr class="even"><td>├─Api</td><td>api模块</td></tr>
                    <tr class="add"><td>├─Application</td><td>框架项目根目录</td></tr>
                    <tr class="even"> <td>&nbsp;&nbsp;&nbsp;&nbsp;├─Common</td><td>项目配置,公共函数</td></tr>
                    <tr class="add"><td>&nbsp;&nbsp;&nbsp;&nbsp;├─Helper</td><td>项目助手类</td></tr>
                    <tr class="even"><td>&nbsp;&nbsp;&nbsp;&nbsp;├─Library</td><td>项目类库</td></tr>
                    <tr class="add"><td>&nbsp;&nbsp;&nbsp;&nbsp;├─Module</td><td>项目模块根目录</td></tr>
                    <tr class="even"><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├─Controller</td><td>控制器</td></tr>
                    <tr class="add"><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├─Logic</td><td>逻辑层</td></tr>
                    <tr class="even"><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├─Model</td><td>模型层</td></tr>
                    <tr class="add"><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└─View</td><td>视图层</td></tr>
                    <tr class="even"><td>&nbsp;&nbsp;&nbsp;&nbsp;├─System</td><td>框架底层目录</td></tr>
                    <tr class="add"><td>&nbsp;&nbsp;&nbsp;&nbsp;└─View</td><td>公共视图</td></tr>
                    <tr class="even"><td>├─Public</td><td>开放目录,index.php</td></tr>
                    <tr class="add"><td>└─Vendor</td><td>扩展</td></tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
