<div id="gird">
    <div class="inner">
        <div class="book-title"><h1>第一章 入门</h1></div>
        <hr>
        <div class="book-content">
            <h2>环境要求</h2>
            因为本框架运用了命名空间,匿名函数等5.3以上特性,所以只支持php5.3以上版本,可运行于包括Apache、IIS和nginx在内的多种WEB服务器和模式,
            目前仅支持Mysql数据库链接(个人能力有限,其他数据库支持后期开发,敬请期待)
            <h2>获取框架</h2>
            <a href="https://github.com/gpYang/ygp">框架下载地址</a>
        </div>
    </div>
</div>
