<!DOCTYPE html PUBliC "-//W3C//dtD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/dtD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta content="favicon.ico" itemprop="image"/>
        <link rel="shortcut icon" href="favicon.ico" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>helloYGP</title>
        <link href="<?php echo $this->staticFile('css', 'layout.css') ?>" type="text/css" rel="stylesheet">
        <link href="<?php echo $this->staticFile('css', 'book.css') ?>" type="text/css" rel="stylesheet">
        <link href="<?php echo $this->staticFile('css', 'prettify.css') ?>" type="text/css" rel="stylesheet">
        <link href="<?php echo $this->staticFile('css', 'ThinkBox.css') ?>" type="text/css" rel="stylesheet">
    </head>
    <body>
        <div id="header">
            <div id="innerHeader">
                <div class="book-top cf">
                    <div class="book-logo fl">
                        <a href="/manual.html" book="1">YGP框架开发手册</a>
                    </div>
                    <div class="right fr">
                        <div class="user-current"></div>
                    </div>
                </div>
            </div>
        </div>
        <?php $this->view($this->_data, 'manual/index/menu') ?>
        <?php echo $this->content; ?>
    </body>
</html>