<div id="gird">
    <div class="inner">
        <div class="book-title"><h1>3.2 事务管理器</h1></div>
        <hr>
        <div class="book-content">
            <div>
                事务管理器是本框架的重中之重,整个框架的运行都是围绕着事务管理器运行的,它管理着框架的所有运行步骤
                可以支持在框架运行的任意阶段添加事件而不需要修改框架底层代码<br>
                在前面<a href="/manual/config-events.html">2.2 事务配置</a><a href="/manual/config-module.html">2.3 模块配置</a>介绍的都是
                事务管理器的配置,通过配置大概都可以知道事务管理器是如何运转的,
                
            </div>
        </div>
    </div>
</div>
