<div id="gird">
    <div class="inner">
        <div class="book-title"><h1>3.2 事务管理器</h1></div>
        <hr>
        <div class="book-content">
            <div>
                &nbsp;&nbsp;&nbsp;&nbsp;事务管理器是本框架的重中之重,整个框架的运行都是围绕着事务管理器运行的,它管理着框架的所有运行步
                骤可以支持在框架运行的任意阶段添加事件而不需要修改框架底层代码<br>
                &nbsp;&nbsp;&nbsp;&nbsp;在前面<a href="/manual/config-events.html">2.2 事务配置</a>&nbsp;&nbsp;&nbsp;<a href="/manual/config-module.html">2.3 模块配置</a>介绍的都是事务管理器的配置,通过配置大概都可以知道事务管理器是
                如何运转的,原本是把事务管理器做成监听者模式的,但考虑到这样需要在框架底层添加代码去派发事件,到项
                目庞大的时候.底层和逻辑会混在一块,导致管理起来比较麻烦,为了实现底层与项目完全分离,将事务管理器做
                成伪监听者模式,完全通过配置来控制执行顺序.<br>
                &nbsp;&nbsp;&nbsp;&nbsp;
            </div>
        </div>
    </div>
</div>
